### ISSUE TITLE
how to build this on linux

### ISSUE THREAD

**Issue by 2439905184** [TimothyGu/libgnurx#1]
I want to use imhex.
but opensuse leap 15.2's glibc version is not heigh enough.It need glibc 2.7.
So the developer recommand me to build it by my self.
but this lib is in nedded. I can't find libgnurx (rpm) from package manager (yast,zypper).
I searched agian and agin,did't know where to install  this lib.
this repo seemes is used to build dll for windows ,not for linux

**Comment by TimothyGu** [comment]
Indeed, the "libgnurx" library was created solely for usage on Windows. You might get away with changing configure.ac and Makefile.in to make it work on Linux, but a better and easier way is really to just use another Linux distribution with more up-to-date packages. I recommend [Debian](https://www.debian.org/), [Ubuntu](https://ubuntu.com/download/desktop), or [Manjaro Linux](https://manjaro.org/).
